server:
  port: 8000

spring:
  application:
    name: msa-gateway
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      routes:
        - id : member-service-sign-up
          uri : lb://MSA-MEMBER
          predicates:
            - Path=/member-service/member/sign-up
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}  # == /member-service/users -> /member
        - id: member-service-sign-in
          uri: lb://MSA-MEMBER
          predicates:
            - Path=/member-service/member/sign-in
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MSA-MEMBER
          predicates:
            - Path=/member-service/member/**
          filters:
            - PreGatewayAuthorizationFilter
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        - id: product-service
          uri: lb://MSA-PRODUCT
          predicates:
            - Path=/product-service/product/**
          filters:
            - PreGatewayAuthorizationFilter
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}
#              args: # Config 클래스에 사용할 멤버변수 정의
#                headerName: Authorization
#                granted: Bearer

logging:
  level:
    ROOT: info
    org:
      springframework:
        web: error

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:18080/eureka

oAuth:
  jwt:
    access-token:
      secret-key: yhjung04#
      expired: 10800
      before-refresh: 1800

    refresh-token:
      secret-key: yeonhoj20#
      expired: 604800000

